image: node:alpine
pipelines:
  default:
    - step:
        name: Syntax checking (eslint)
        script:
          - yarn
          - yarn lint
    - step:
        name: Unit Testing (jest)
        script:
          - yarn
          - yarn test
